# kcare0 param.yaml
lm_control_node:
  ros__parameters:
    port: "/dev/ttyLM"
    baudrate: 19200
    offset_position: 107.33
    global_speed: 5000
    initial_speed: 1000
    elevation_range: [107.33, 690.]
    home_position: 118.33
