# kcare0 param.yaml
lm_control_node:
  ros__parameters:
    port: "/dev/ttyLM"
    baudrate: 19200
    offset_position: 103.9
    global_speed: 100.0
    initial_speed: 10.0
    elevation_range: [108., 675.]
    home_position: 113.9
    encoder_ppr: 16384
    reduction_ratio: 1.4736842 # reduction_ratio = 28 / 19
    lead_pitch: 10
    rpm_range: [-3000, 3000]
    limit_inveted: False
    motor_inv: True